### ISSUE TITLE
SQL to Caml parser is not happy about escaped quotes

### ISSUE THREAD

**Issue by petero-dk** [Aymkdn/SharepointPlus#89] opened 2018-01-10 16:06 UTC
```
Parent = "Support and deliver roll out of \"Sale Management\"" AND ID <> 400
```
When parsed becomes
```
<Eq><FieldRef Name="Parent" /><Value Type="Text">Support and deliver roll out of "Sale ManagementNull AND ID&lt;&gt;400</Value></Eq>
```
It seems to affect the second escaped " 
If I switch around and use single ' they do have the same problem if the ' is the last item in the quotations.

```
Parent = 'transletsen af matrialeBy O\'Conner and O\''
<Eq><FieldRef Name="Parent" /><Value Type="Text">transletsen af matrialeBy O'Conner and O**Null**</Value></Eq>
```
Actually the problem is having the same escaped character as the quotation character in a where clause

**Comment by Aymkdn** [comment] 2018-01-10 16:28
Can you show me the full query that you try to parse ?

**Comment by Aymkdn** [comment] 2018-01-10 16:37
I'll assume it's : 
`"Parent = 'Support and deliver roll out of \"Sale Management\"' AND ID <> 400"`

In that case you can proceed this way:
```javascript
$SP().list("The List").get({
  whereCAML:true,
  where:$SP().parse("Parent = 'Support and deliver roll out of &quot;Sale Management&quot;' AND ID <> 400", false)
})
```

So you replace the quotes by `&quot;`, and you use [$SP().parse()](https://aymkdn.github.io/SharepointPlus/lists.html#parse)

**Comment by petero-dk** [comment] 2018-01-10 18:15
I cannot do that. These are dynamic generated queries so I do not know which other chars that needs to be escaped. The weird thing is that it is only an issue when the escaped ' or " are followed by a non-escaped ' or " respectively. 

When it is the last item in this loop: #L820
```
 var apos = letter;
            var word = "", other="";
            while ((letter = queryString.charAt(++i)) != apos && i < limitMax) {
              if (letter == "\\") letter = queryString.charAt(++i);
              word+=letter;
}
```
If you notice in my samples it inserts a null instead of the escaped " or '

**Comment by Aymkdn** [comment] 2018-01-10 19:31
What is your code exactly?

Because if I do this: 
```javascript
var parent = 'Support and deliver roll out of "Sale Management"';
var id = 400;
var where = $SP().parse("Parent = '"+parent+"' AND ID <> "+id);
console.log(where); // -> <And><Eq><FieldRef Name="Parent" /><Value Type="Text">Support and deliver roll out of "Sale Management"</Value></Eq><Neq><FieldRef Name="ID" /><Value Type="Number">400</Value></Neq></And>
$SP().list("The List").get({
  where:where
})
.then(function(data) {
  console.log(data.length); // -> return X
})
```

Then it does work...

**Comment by Aymkdn** [comment] 2018-01-11 20:09
So, is it OK now?

**Comment by petero-dk** [comment] 2018-01-11 20:19
Hi @Aymkdn 

As I have tried to explain above, this is a narrow case, but not okay. The workaround you describe is also the one I have temporarily implemented already, however what I tried to describe is a bug in the code.

```
var parent = "Support and deliver roll out of \\'Sale Management\\'";
var id = 400;
var where = $SP().parse("Parent = '"+parent+"' AND ID <> "+id);
console.log(where); // -> <And><Eq><FieldRef Name="Parent" /><Value Type="Text">Support and deliver roll out of "Sale Management"</Value></Eq><Neq><FieldRef Name="ID" /><Value Type="Number">400</Value></Neq></And>
$SP().list("The List").get({
  where:where
})
.then(function(data) {
  console.log(data.length); // -> return X
})
```

and 

```
var parent = 'Support and deliver roll out of \\"Sale Management\\"';
var id = 400;
var where = $SP().parse('Parent = "'+parent+'" AND ID <> '+id);
console.log(where); // -> <And><Eq><FieldRef Name="Parent" /><Value Type="Text">Support and deliver roll out of "Sale Management"</Value></Eq><Neq><FieldRef Name="ID" /><Value Type="Number">400</Value></Neq></And>
$SP().list("The List").get({
  where:where
})
.then(function(data) {
  console.log(data.length); // -> return X
})
```

will always fail, because of the escaped " or ' inside the " or ' in the query. Because the `var parent` is dynamic I **can** always end up in one of the edge cases, no matter which I choose. 

Does that make sense? The output in my original post (after I have cleaned up a little)  directly  from my code. The `Null` in the output text is coming from the `parse` function

**Comment by petero-dk** [comment] 2018-01-11 20:21
The output from the parse function will for the var parent above be:

`...<Value Type="Text">Support and deliver roll out of "Sale ManagementNull AND ID&lt;&gt;400</Value>...`

**Comment by Aymkdn** [comment] 2018-01-12 15:23
Actually the issue is due to `\''`. Example: 
> "Title = 'James O\\'Connor and O\\'' AND ID <> 0
>  _________________________________ ^  

The `''` will be converted in `Null`. I'll look at this to provide a fix for next release (v5.1)

**Comment by Aymkdn** [comment] 2018-01-12 15:32
If you want to test, replace [ligne 694](https://github.com/Aymkdn/SharepointPlus/blob/master/sharepointplus-5.0.js#L694) by : 
```javascript
var queryString = q.replace(/(\s+)?(=|~=|<=|>=|<>|<|>| LIKE | IN )(\s+)?/g,"$2").replace(/([^\\?])""|([^\\?])''/g,"$1Null").replace(/==/g,"="); // remove unnecessary white space & replace '
```

And let me know please !

**Comment by Aymkdn** [comment] 2018-01-15 13:26
Did you get a chance to test it @petero-dk  ?

**Comment by petero-dk** [comment] 2018-01-15 13:27
Not yet, been away since. On my todo when I get back

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Aymkdn** [comment] 2018-01-20 07:54
OK. Please let me know when you get back :-)

**Comment by Aymkdn** [comment] 2018-01-23 11:24
Sorry to hurry you, but it's been a while now and I'd like to close this issue.

If you don't reply soon, then I'll assume it works OK with this fix and it will be released for v5.1.

Thanks.

**Comment by petero-dk** [comment] 2018-01-23 11:29
Ill check today

**Comment by Aymkdn** [comment] 2018-01-26 09:55
No news, so I'm closing it. Feel free to comment back if you want to.

Thanks for reporting back this issue!

**Closed by Aymkdn** 2018-01-26 09:55 UTC
